_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: True
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    DEPTH: 101
DATASETS:
  TRAIN: ("synthtext1",) 
  TEST: ("synthtext1",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (100000,)
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 5000

INPUT:
  MIN_SIZE_TRAIN: (800,900,1000,1100,1200)
  MAX_SIZE_TRAIN: 1200
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1500

OUTPUT_DIR: "./out_dir_r101/pre_model/"

# please register your synthtext datasets in detectron2/data/datasets/builtin.py.
# because of the limit of memory, we split synthtext into several subsets for training, such as synthtext1.
# we adjust the learning rate dynamically

